### ISSUE TITLE
Missing useful time for CG

### ISSUE THREAD

**Issue by aristeidis-mastoras** [Algebraic-Programming/ALP#166]
The useful time is not reported for CG when the algorithm does not converge. The bug was introduced when the returned code was correctly changed from SUCCESS to FAILED. However, the useful time should still be reported as we often set a threshold for the maximum number of iterations when evaluating the algorithm, and the useful time is still valid even if the algorithm did not converge.

**Comment by anyzelman** [comment]
Hi Aristeidis! Should this one be resolved before merging #164 , or are they independent? (The latter right?)

**Comment by anyzelman** [comment]
Fixed and merged into develop (MR #218 ).
