### ISSUE TITLE
hyperdags output as a scalar

### ISSUE THREAD

**Issue by byjtew** [Algebraic-Programming/ALP#219]
In order to complete #188 (matrix-to-scalar reduction), we need the *hyperdags* backend to handle scalar as outputs.

**Comment by anyzelman** [comment]
Also output iterators should ideally be registered as output?

**Comment by byjtew** [comment]
> Also output iterators should ideally be registered as output?

I am not sure to understand what you mean by that

**Comment by anyzelman** [comment]
So when we do something like

```
grb::Vector< double > x( 50 );
// do some computations that create interesting output in x
for( const auto &pair : x ) {
   // process output of x
}
```
The last for-loop of course implicitly calls `x.cbegin();`. This call is currently not recorded in the HyperDAGs backend, but probably should -- it indicates that the contents of x at that point are used outside of ALP. This is similar to the current status where e.g. `grb::dot( z, ... )` does not record `z` as output either.

**Comment by byjtew** [comment]
> 

I see, that would be interesting to have indeed. I'll try that.
