### ISSUE TITLE
Possible bug in output_verification function

### ISSUE THREAD

**Issue by alberto-scolari** [Algebraic-Programming/ALP#234]
By running the `conjugate_gradient` test as in our test suite

```bash
./tests/smoke/conjugate_gradient_reference ../datasets/gyro_m.mtx direct 1 1 verification ../tests/smoke/output_verification/conjugate_gradient_out_gyro_m_ref
```

the following output appears

```bash
Test executable: ./tests/smoke/conjugate_gradient_reference
Executable called with parameters ../datasets/gyro_m.mtx, inner repititions = 1, and outer reptitions = 1
Time since epoch (in ms.): 1691183265938
Info: grb::init (reference) called.
Info: MatrixMarket file detected. Header line: ``%%MatrixMarket matrix coordinate real symmetric''
Info: MatrixFileReader constructed for ../datasets/gyro_m.mtx: an 17361 times 17361 matrix holding 178896 entries. Type is MatrixMarket and the input is symmetric.
Info: nonzero check skipped as the number of nonzeroes cannot be derived from the matrix file header. The grb::Matrix reports 340431 nonzeroes.
Time taken for a 1 Conjugate Gradients calls (hot start): 5131.47. Error code is 0
        number of CG iterations: 7200
        milliseconds per iteration: 0.712704
Outer iteration #0 timings (io, preamble, useful, postamble, time since epoch): 0.092928, 180.402898, 5131.466073, 0.002431, 1691183272251
Overall timings (io, preamble, useful, postamble):
Avg: 9.292800e-02, 1.804029e+02, 5.131466e+03, 2.431000e-03
Min: 9.292800e-02, 1.804029e+02, 5.131466e+03, 2.431000e-03
Max: 9.292800e-02, 1.804029e+02, 5.131466e+03, 2.431000e-03
Std: -nan, -nan, -nan, -nan
Time since epoch (in ms.): 1691183273251
Info: grb::finalize (reference) called.
Benchmark completed successfully and took 7200 iterations to converge with residual 1.52328e-08.
Error code is 0.
Size of x is 17361.
First 10 nonzeroes of x are: ( 5.60929e+10 5.60929e+10 5.60929e+10 3.78268e+10 3.78268e+10 3.78268e+10 7.94409e+10 7.94409e+10 7.94409e+10 2.56607e+10 )
Info: output vector passed 2-norm verification
        2-norm is 0.104883 which is smaller or equal to the effective relative tolerance of 9.99523e+10
Info: output vector passed inf-norm verification
        inf-norm is 0.0117188 which is smaller or equal to the effective relative tolerance of 2.67043e+09
Output vector verificaton was successful!
Test OK
```

This is a bit suspicious, because the maximum inf-norm tolerated is `2.67043e+09`, which seems a bit generous to me. The same holds for the 2-norm. Looking at the code https://github.com/Algebraic-Programming/ALP/blob/master/tests/utils/output_verification.hpp#L321 this is not just a mistake while printing, but the "generous" value is the one being used in the actual check https://github.com/Algebraic-Programming/ALP/blob/master/tests/utils/output_verification.hpp#L309

@alberto-scolari @djelovina is this normal?

**Comment by anyzelman** [comment]
@djelovina -- could you maybe have a quick look on this one?

**Comment by djelovina** [comment]
Correct me if I'm wrong @alberto-scolari  and @anyzelman , I guess the confusion here comes from very large number called  _effective relative tolerance_, in our example of **gyro_m.mtx** with value  `eff_rel_tol=9.99523e+10`? 
This number is defined as  `eff_rel_tol=(c1 * magnitude2 + n * eps)`, where `c1=0.0001`, `n=17361` , `eps=2.22045e-16` and `magnitude2` is the 2-norm  of the reference solution vector, i.e. `magnitude2=|v_ref|`. The test checks if, for the solution vector `v`, the expression `|v-v_ref|< (c1 * |v_ref| + n * eps) `, holds. In this example  `c1 * |v_ref| >> n * eps`, which simplifies the assertion to  `|v-v_ref|/|v_ref|< c1`, or equivalent of  `c1=0.01%` precision with respect to the reference solution.  Similar considerations applies to the infNorm.

**Comment by anyzelman** [comment]
Yeah exactly. Given I wrote that code ages ago, it's better if someone else independently verifies there is no error in the logic, and that for this matrix in particular all is fine

**Comment by djelovina** [comment]
I think tests properly check that the  numerical error, relative to the reference solution, is less than `0.01%` . Perhaps the verification message be more clear. I don't see any other problem here.

**Comment by anyzelman** [comment]
OK then lemme close this one without further ado (clearing bug flags before v0.8)-- @alberto-scolari please update if you think that's premature (and if so, why). Thanks both!
