### ISSUE TITLE
Failing assertion in BSP1D exec routine

### ISSUE THREAD

**Issue by alberto-scolari** [Algebraic-Programming/ALP#235]
This assertion fails

https://github.com/Algebraic-Programming/ALP/blob/dbe9a76ad9ba56e7bb6a19a98a32761083a15281/include/graphblas/bsp1d/exec.hpp#L88

and it is probably wrong: indeed, the value is for all processes `sizeof(T)`.

Furthermore, at line

https://github.com/Algebraic-Programming/ALP/blob/dbe9a76ad9ba56e7bb6a19a98a32761083a15281/include/graphblas/bsp1d/exec.hpp#L209

there is a memory leak, since the variable `data_in` is allocated but never freed.

finally, the routines `_grb_exec_spmd` and `_grb_exec_varin_spmd` are almost identical, and can probably be refactored to avoid duplicated bugs.

**Comment by anyzelman** [comment]
Related issues fixed in #239 , this issue should no longer apply
