### ISSUE TITLE
Failed call of eWiseLambda 

### ISSUE THREAD

**Issue by aleksamilisavljevic** [Algebraic-Programming/ALP#289]
Added a test that fails on call of `eWiseLambda`:

https://github.com/Algebraic-Programming/ALP/blob/f2bd190839616067ce9be32ec1092a3fd5daf431/tests/unit/eWiseLambda.cpp#L53

I think that this line of code causes an issue:

https://github.com/Algebraic-Programming/ALP/blob/f2bd190839616067ce9be32ec1092a3fd5daf431/include/graphblas/reference/blas2.hpp#L2611

**Comment by anyzelman** [comment]
I confirm that the call should not fail (except for maybe a casting / loss of precision warning). Will therefore remove invalid (I'm all but sure this is a confirmed bug), and will set the milestone for v0.8. Many thanks!!

**Comment by anyzelman** [comment]
I also can't get the idea of that if-statement. Removing it both in my mind as well as via your unit test should induce the correct behaviour. The fix just now pushed was also your idea @aleksamilisavljevic right?
